name: CI

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ matrix.lua_version }}-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true

    strategy:
      matrix:
        lua_version: [ 5.1 ]
        luacheck_version: [ 1.2.0 ]

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: install lua ${{ matrix.lua_version }}
        uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: ${{ matrix.lua_version }}

      - name: install luarocks
        uses: leafo/gh-actions-luarocks@v6

      - name: install luacheck ${{ matrix.luacheck_version }}
        run: luarocks install luacheck ${{ matrix.luacheck_version }}

      - run: make lint

  check:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ matrix.nvim_version }}-${{ matrix.luals_version }}-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true

    strategy:
      matrix:
        nvim_version: [ stable, nightly ]
        luals_version: [ 3.15.0 ]

    env:
      VIMRUNTIME: /home/runner/nvim-${{ matrix.nvim_version }}/share/nvim/runtime

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: install nvim ${{ matrix.nvim_version }}
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim_version }}

      - name: install lua-language-server ${{ matrix.luals_version }}
        run: |
          mkdir -p luals
          curl -L "https://github.com/LuaLS/lua-language-server/releases/download/${{ matrix.luals_version }}/lua-language-server-${{ matrix.luals_version }}-linux-x64.tar.gz" | tar zx --directory luals
          echo "luals/bin" >> "$GITHUB_PATH"

      - run: make check

      - run: make help-check

      - run: make style

      - run: make style-doc
